options:
  # Makes it easier to include files from third-party projects installed via npm.
  # Ex.
  #   1. `npm install hex-framework`
  #   2. Add `@import 'hex-framework/scss/hex';` to
  #      `html/site/themes/{{ your_theme }}/sass/{{ your_theme }}.scss`.
  loadPath: 'node_modules'




serve:
  files:
    -
      expand: true,
      cwd:    '<%= m.local.themePath %>/sass'
      dest:   '<%= m.local.themePath %>/css'
      ext:    '.css'
      src:
        - '*.scss'
  options:
    lineNumbers: true
    style:       expanded


build:
  files:
    -
      expand: true,
      cwd:    '<%= m.local.themePath %>/sass'
      dest:   '<%= m.local.themePath %>/css'
      ext:    '.css'
      src:
        - '*.scss'
  options:
    sourcemap: none
    style:     compressed
    update:    true
